#! /bin/sh

#Rose Pine Moon Colors
bspc config normal_border_color "#908caa"
bspc config focused_border_color "#9ccfd8"

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI


bspc config border_width 2
bspc config window_gap 6


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_action2 resize_corner

bspc rule -a Thunar state=floating
bspc rule -a Yad state=floating
bspc rule -a Gucharmap state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Mpdevil state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled

# bspc rule -a mpv state=floating
bspc rule -a Sxiv state=floating

# wmname LG3D   #for java applications
xsetroot -cursor_name left_ptr #mouse
mpc random on &
nm-applet &
blueman-applet &
# feh --bg-scale wallpaper/newton.png &

feh --bg-scale ~/wallpaper/pexels-eberhardgross-640781.jpg

~/.config/polybar/simple.sh &
picom -f &
xss-lock -- betterlockscreen -l &
nvim --headless +q 
